# Generated by Django 5.1.4 on 2024-12-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_alter_category_options_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='1', max_length=30),
        ),
    ]
