# Generated by Django 5.1.4 on 2024-12-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0005_remove_customer_email_remove_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
