# Generated by Django 5.1.4 on 2024-12-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0007_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cart_items',
            field=models.JSONField(default=dict),
        ),
    ]
