# Generated by Django 5.1.4 on 2024-12-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0010_remove_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
